<?php

namespace Simple\ProfileBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{

    public function findByIdUser($id)
    {
        $todos = $this->createQueryBuilder('t')
            ->leftJoin('t.user', 'u')
            ->select(
                't.id',
                't.name',
                't.description',
                't.date_todo'
            )
            ->where('u.id = :id')
            ->setParameter('id', $id)
            ->distinct()
            ->getQuery()
            ->getResult();

        return $todos;
    }

    public function deleteById($id){

        return $this->createQueryBuilder('t')
            ->delete()
            ->where('t.id = :id')
            ->setParameter('id', $id)
            ->distinct()
            ->getQuery()
            ->getResult();

    }





}
